### ISSUE TITLE
assets:precompile  No implicit conversion of nil into string

### ISSUE THREAD

**Issue by rxever** [alchapone/polymer-elements-rails#7]
Hey, so I'm getting this error when compiling assets. Does anyone have any idea what should be done to avoid the errors? Would be grateful for any hints or suggestions! Thank you.

In my gemfile I have: 

```
gem 'polymer-rails', '>=1.0.3'
gem 'polymer-elements-rails', '>=1.0.0.pre.rc.1'
```

And in my application.html.erb file I have:

```
//= require polymer/polymer
//= require paper-button/paper-button
//= require paper-input/paper-input
//= require paper-checkbox/paper-checkbox
```

I am using rails  4.2.3 and ruby ruby 2.1.3p242 

```
C:\project>bundle exec rake assets:precompile --trace
DL is deprecated, please use Fiddle
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
I, [2015-08-12T13:49:41.567877 #8284]  INFO -- : ** [Raven] Raven 0.13.1 configured not to send errors.
** Execute assets:precompile
rake aborted!
TypeError: no implicit conversion of nil into String
  (in C:/Ruby21/lib/ruby/gems/2.1.0/gems/polymer-elements-rails-1.0.0.pre.rc.1/app/assets/components/gold-cc-cvc-input/test/basic.html)
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:264:in `initialize'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:264:in `new'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:264:in `find_asset'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:61:in `find_asset'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/environment.rb:75:in `find_asset'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/polymer-rails-1.0.3/lib/polymer-rails/processors/components_processor.rb:62:in `find_asset'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/polymer-rails-1.0.3/lib/polymer-rails/processors/components_processor.rb:42:in `asset_content'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/polymer-rails-1.0.3/lib/polymer-rails/processors/components_processor.rb:30:in `block in inline_javascripts'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/polymer-rails-1.0.3/lib/polymer-rails/processors/components_processor.rb:29:in `each'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/polymer-rails-1.0.3/lib/polymer-rails/processors/components_processor.rb:29:in `inline_javascripts'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/polymer-rails-1.0.3/lib/polymer-rails/processors/components_processor.rb:14:in `process'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/polymer-rails-1.0.3/lib/polymer-rails/railtie.rb:20:in `block (2 levels) in <class:Railtie>'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/processor.rb:29:in `call'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/processor.rb:29:in `evaluate'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:197:in `block in evaluate'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:194:in `each'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:194:in `evaluate'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:12:in `initialize'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `new'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `block in build_asset'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:395:in `circular_call_protection'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:373:in `build_asset'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:94:in `block in build_asset'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/caching.rb:58:in `cache_asset'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:93:in `build_asset'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:287:in `find_asset'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:61:in `find_asset'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/bundled_asset.rb:16:in `initialize'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:377:in `new'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:377:in `build_asset'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:94:in `block in build_asset'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/caching.rb:58:in `cache_asset'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:93:in `build_asset'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:287:in `find_asset'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:61:in `find_asset'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:211:in `block in find_asset'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:257:in `benchmark'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:210:in `find_asset'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:119:in `block in compile'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:118:in `each'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:118:in `compile'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/rake/sprocketstask.rb:146:in `with_logger'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
C:/Ruby21/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
C:/Ruby21/bin/rake:23:in `load'
C:/Ruby21/bin/rake:23:in `<main>'
Tasks: TOP => assets:precompile
```

**Comment by leehankyeol** [comment]
@rxever How did you solve the problem, or what was the problem? I'm having exactly the same issue.

**Comment by rxever** [comment]
I did this:
`
gem 'polymer-rails', '~>1.1.0'
gem 'polymer-elements-rails', github: 'tikitikifoofoo/polymer-elements-rails'
`
